name: Lint SSHd Dockerfile

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker/Dockerfile.sshd'
      - '.github/workflows/docker-sshd.yml'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docker/Dockerfile.sshd'

jobs:
  lint-sshd-dockerfile:
    runs-on: ubuntu-latest
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v3
      - 
        name: Lint Dockerfile
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'docker/Dockerfile.sshd'
